import localFont from "next/font/local";

import "./globals.css";

const myFont = localFont({
  src: "../../public/fonts/SF-Pro-Display-Regular.ttf",
});

export const metadata = {
  title: "Deaily Hub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={myFont.className}>{children}</body>
    </html>
  );
}
